Release MiniOS live-config 11.0.5.14

diff --git a/components/0040-sudo b/components/0040-sudo
--- a/components/0040-sudo
+++ b/components/0040-sudo
@@ -23,6 +23,10 @@ Cmdline ()
 				LIVE_CONFIG_NOROOT="true"
 				;;
 
+			live-config.sudo-mode=*|sudo-mode=*)
+				LIVE_SUDO_MODE="${_PARAMETER#*sudo-mode=}"
+				;;
+
 			live-config.username=*|username=*)
 				LIVE_USERNAME="${_PARAMETER#*username=}"
 				;;
@@ -52,6 +56,15 @@ Init ()
 
 Config ()
 {
+	case "${LIVE_SUDO_MODE}" in
+		""|passwordless|password|disabled)
+			;;
+		*)
+			echo "Invalid LIVE_SUDO_MODE=${LIVE_SUDO_MODE}; using passwordless" >&2
+			LIVE_SUDO_MODE="passwordless"
+			;;
+	esac
+
 	# Skip sudo configuration if username is root
 	case "${LIVE_USERNAME}" in
 		root)
@@ -59,13 +72,27 @@ Config ()
 			;;
 	esac
 
+	if [ "${LIVE_SUDO_MODE}" = "disabled" ]
+	then
+		rm -f /etc/sudoers.d/live
+		touch /var/lib/live/config/sudo
+		exit 0
+	fi
+
 	# Checking if package is already configured differently
 	if grep -qs "^${LIVE_USERNAME}" /etc/sudoers.d/live
 	then
 		exit 0
 	fi
 
-	echo "${LIVE_USERNAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/live
+	case "${LIVE_SUDO_MODE}" in
+		password)
+			echo "${LIVE_USERNAME} ALL=(ALL:ALL) ALL" >> /etc/sudoers.d/live
+			;;
+		*)
+			echo "${LIVE_USERNAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/live
+			;;
+	esac
 	chmod 0440 /etc/sudoers.d/live
 
 	# Add the user to the sudo group even if it's not required for
diff --git a/components/1080-policykit b/components/1080-policykit
--- a/components/1080-policykit
+++ b/components/1080-policykit
@@ -22,6 +22,9 @@ Cmdline ()
 			live-config.noroot|noroot)
 				LIVE_CONFIG_NOROOT="true"
 				;;
+			live-config.polkit-mode=*|polkit-mode=*)
+				LIVE_POLKIT_MODE="${_PARAMETER#*polkit-mode=}"
+				;;
 
 			live-config.username=*|username=*)
 				LIVE_USERNAME="${_PARAMETER#*username=}"
@@ -52,6 +55,23 @@ Init ()
 
 Config ()
 {
+	case "${LIVE_POLKIT_MODE}" in
+		""|passwordless|password|disabled)
+			;;
+		*)
+			echo "Invalid LIVE_POLKIT_MODE=${LIVE_POLKIT_MODE}; using passwordless" >&2
+			LIVE_POLKIT_MODE="passwordless"
+			;;
+	esac
+
+	case "${LIVE_POLKIT_MODE}" in
+		password|disabled)
+			rm -f /usr/share/polkit-1/rules.d/sudo_on_live.rules
+			touch /var/lib/live/config/policykit
+			exit 0
+			;;
+	esac
+
 	# Configure PolicyKit in live session
 	mkdir -p /usr/share/polkit-1/rules.d
 
